# use Docker-based container (instead of OpenVZ)
sudo: false

language: scala

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

jobs:
  include:
     - stage: openjdk8
       name: "test and docs on jdk8"
       script: sbt ++$TRAVIS_SCALA_VERSION test doc
       arch: amd64
     - stage: openjdk11
       name: "test and docs on jdk11"
       script: sbt ++$TRAVIS_SCALA_VERSION test doc
       env: TRAVIS_JDK=11
       arch: amd64
     - stage: openjdk8
       name: "test and docs on jdk8"
       script: sbt ++$TRAVIS_SCALA_VERSION test doc
       arch: ppc64le
     - stage: openjdk11
       name: "test and docs on jdk11"
       script: sbt ++$TRAVIS_SCALA_VERSION test doc
       env: TRAVIS_JDK=11
       arch: ppc64le


env:
  global:
    - TRAVIS_JDK=8

before_cache:
  # Remove to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk
